var annotated_dup =
[
    [ "AppModel", "class_app_model.html", "class_app_model" ],
    [ "ChessApplication", "class_chess_application.html", "class_chess_application" ],
    [ "ChessBoard", "class_chess_board.html", "class_chess_board" ],
    [ "ChessEdit", "class_chess_edit.html", "class_chess_edit" ],
    [ "ChessEngine", "class_chess_engine.html", "class_chess_engine" ],
    [ "ChessInfo", "class_chess_info.html", "class_chess_info" ],
    [ "ChessWindow", "class_chess_window.html", "class_chess_window" ],
    [ "ColourChooser", "class_colour_chooser.html", "class_colour_chooser" ],
    [ "DialogColours", "class_dialog_colours.html", "class_dialog_colours" ],
    [ "DialogInput", "class_dialog_input.html", "class_dialog_input" ],
    [ "DialogPieceValues", "class_dialog_piece_values.html", "class_dialog_piece_values" ],
    [ "FENTranslator", "class_f_e_n_translator.html", "class_f_e_n_translator" ],
    [ "GUIColourChooser", "class_g_u_i_colour_chooser.html", "class_g_u_i_colour_chooser" ],
    [ "GUIPieceValues", "class_g_u_i_piece_values.html", "class_g_u_i_piece_values" ],
    [ "GUITimeInputter", "class_g_u_i_time_inputter.html", "class_g_u_i_time_inputter" ],
    [ "MockColourChooser", "class_mock_colour_chooser.html", "class_mock_colour_chooser" ],
    [ "MockPieceValues", "class_mock_piece_values.html", "class_mock_piece_values" ],
    [ "MockTimeInputter", "class_mock_time_inputter.html", "class_mock_time_inputter" ],
    [ "PieceValues", "class_piece_values.html", "class_piece_values" ],
    [ "STColours", "struct_s_t_colours.html", "struct_s_t_colours" ],
    [ "STGameState", "struct_s_t_game_state.html", "struct_s_t_game_state" ],
    [ "STInfo", "struct_s_t_info.html", "struct_s_t_info" ],
    [ "STInput", "struct_s_t_input.html", "struct_s_t_input" ],
    [ "STMove", "struct_s_t_move.html", "struct_s_t_move" ],
    [ "STPieceValues", "struct_s_t_piece_values.html", "struct_s_t_piece_values" ],
    [ "STSquare", "struct_s_t_square.html", "struct_s_t_square" ],
    [ "TestApplication", "class_test_application.html", "class_test_application" ],
    [ "TestColourChooser", "class_test_colour_chooser.html", "class_test_colour_chooser" ],
    [ "TestFENTranslator", "class_test_f_e_n_translator.html", "class_test_f_e_n_translator" ],
    [ "TestPieceValues", "class_test_piece_values.html", "class_test_piece_values" ],
    [ "TestSTHalveMove", "class_test_s_t_halve_move.html", "class_test_s_t_halve_move" ],
    [ "TestTimeInputter", "class_test_time_inputter.html", "class_test_time_inputter" ],
    [ "TimeInputter", "class_time_inputter.html", "class_time_inputter" ]
];